CREATE TABLE IF NOT EXISTS accounts(
  id VARCHAR(255) NOT NULL primary key COMMENT 'primary key',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Time Created',
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last Update',
  name varchar(255) COMMENT 'User Name',
  email varchar(255) COMMENT 'User Email',
  picture varchar(255) COMMENT 'User Picture'
) default charset utf8 COMMENT '';
CREATE TABLE IF NOT EXISTS knights(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Time Created',
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last Update',
  name VARCHAR(255) NOT NULL,
  weaponType VARCHAR(255) NOT NULL,
  imgUrl TEXT,
  creatorId VARCHAR(255) NOT NULL
) default charset utf8 COMMENT '';
DROP TABLE knights;
CREATE TABLE IF NOT EXISTS castles(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Time Created',
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last Update',
  name VARCHAR(255) NOT NULL,
  location VARCHAR(255) NOT NULL,
  imgUrl TEXT,
  creatorId VARCHAR(255) NOT NULL
) default charset utf8 COMMENT '';
CREATE TABLE IF NOT EXISTS manor(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  castlesId INT NOT NULL,
  knightsId INT NOT NULL,
  FOREIGN KEY (castlesId) REFERENCES castles(id),
  FOREIGN KEY (knightsId) REFERENCES knights(id)
)